# Generated by Django 3.2.18 on 2023-07-22 08:46

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0005_rename_feature_property_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=16)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('price_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
