# Generated by Django 3.2.18 on 2023-07-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='feature',
            new_name='is_featured',
        ),
    ]
